class ArtifactMgmtError(Exception):
    """Base class for all SDK errors."""


class ModelNotFoundError(ArtifactMgmtError): ...
class ModelAlreadyExistsError(ArtifactMgmtError): ...
class VersionNotFoundError(ArtifactMgmtError): ...
class VersionConflictError(ArtifactMgmtError): ...
class IdempotencyMismatchError(ArtifactMgmtError): ...
class ChecksumMismatchError(ArtifactMgmtError): ...
class UploadNotFoundError(ArtifactMgmtError): ...
class AuthError(ArtifactMgmtError): ...
class ServiceError(ArtifactMgmtError): ...
class FrameworkNotInstalledError(ArtifactMgmtError): ...
class UnknownSerializerError(ArtifactMgmtError): ...
